"""Mini SIEM Platform — core engine: ingestion, normalization, detection, alerting."""

from __future__ import annotations

import hashlib
import json
import logging
import re
import threading
import time
from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from pathlib import Path
from typing import Any, Callable

logger = logging.getLogger(__name__)

# ── Severity ──────────────────────────────────────────────────────────────────

class Severity(str, Enum):
    """Alert severity levels."""

    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


# ── Normalized log event ───────────────────────────────────────────────────────

@dataclass(frozen=True)
class LogEvent:
    """Normalized log event fed into the detection engine."""

    event_id: str
    timestamp: datetime
    source: str
    message: str
    raw: str
    fields: dict[str, str] = field(default_factory=dict)

    @staticmethod
    def _make_id(raw: str, ts: datetime) -> str:
        digest = hashlib.sha256(f"{ts.isoformat()}{raw}".encode()).hexdigest()[:16]
        return digest


@dataclass(frozen=True)
class Alert:
    """SIEM alert generated by a detection rule."""

    alert_id: str
    rule_name: str
    severity: Severity
    message: str
    event: LogEvent
    triggered_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))

    def to_dict(self) -> dict[str, Any]:
        """Serialize to dict for JSON output."""
        return {
            "alert_id": self.alert_id,
            "rule_name": self.rule_name,
            "severity": self.severity.value,
            "message": self.message,
            "triggered_at": self.triggered_at.isoformat(),
            "event": {
                "event_id": self.event.event_id,
                "timestamp": self.event.timestamp.isoformat(),
                "source": self.event.source,
                "message": self.event.message,
            },
        }


# ── Detection rules ────────────────────────────────────────────────────────────

@dataclass
class DetectionRule:
    """Regex-based detection rule."""

    name: str
    pattern: re.Pattern[str]
    severity: Severity
    description: str

    def matches(self, event: LogEvent) -> bool:
        """Return True if the rule fires on this event."""
        return bool(self.pattern.search(event.message) or self.pattern.search(event.raw))


BUILTIN_RULES: list[DetectionRule] = [
    DetectionRule(
        name="SSH_BRUTE_FORCE",
        pattern=re.compile(r"Failed password for .* from .* port \d+", re.IGNORECASE),
        severity=Severity.HIGH,
        description="SSH brute-force attempt detected (T1110.001)",
    ),
    DetectionRule(
        name="SUDO_PRIVILEGE_ESCALATION",
        pattern=re.compile(r"sudo:.*COMMAND=", re.IGNORECASE),
        severity=Severity.MEDIUM,
        description="Sudo command execution logged (T1078)",
    ),
    DetectionRule(
        name="ROOT_LOGIN",
        pattern=re.compile(r"session opened for user root", re.IGNORECASE),
        severity=Severity.HIGH,
        description="Direct root login detected (T1078.003)",
    ),
    DetectionRule(
        name="NEW_USER_CREATED",
        pattern=re.compile(r"new user:|useradd|adduser", re.IGNORECASE),
        severity=Severity.HIGH,
        description="New user account created (T1136.001)",
    ),
    DetectionRule(
        name="CRON_MODIFIED",
        pattern=re.compile(r"(crontab|cron\.d|CRON)", re.IGNORECASE),
        severity=Severity.MEDIUM,
        description="Cron job modification detected (T1053.003)",
    ),
    DetectionRule(
        name="POSSIBLE_WEBSHELL",
        pattern=re.compile(r"(cmd=|exec=|shell=|/bin/sh|/bin/bash).{0,50}(HTTP|GET|POST)", re.IGNORECASE),
        severity=Severity.CRITICAL,
        description="Possible webshell execution in HTTP log (T1505.003)",
    ),
    DetectionRule(
        name="AUTHENTICATION_FAILURE",
        pattern=re.compile(r"authentication failure|auth fail|invalid password", re.IGNORECASE),
        severity=Severity.MEDIUM,
        description="Authentication failure (T1110)",
    ),
    DetectionRule(
        name="FILE_DELETION",
        pattern=re.compile(r"rm -rf|shred|wipe|unlink.*(/var|/etc|/home)", re.IGNORECASE),
        severity=Severity.HIGH,
        description="Possible data destruction (T1485)",
    ),
]


# ── Log parsers ────────────────────────────────────────────────────────────────

class LogParser:
    """Base log parser — override parse_line."""

    source_name: str = "generic"

    _TS_FORMATS = (
        "%Y-%m-%dT%H:%M:%S%z",
        "%Y-%m-%d %H:%M:%S",
        "%b %d %H:%M:%S",
    )

    def parse_line(self, line: str) -> LogEvent | None:
        """Parse a single log line into a LogEvent, or return None to skip."""
        line = line.strip()
        if not line:
            return None
        ts = datetime.now(timezone.utc)
        event_id = LogEvent._make_id(line, ts)
        return LogEvent(
            event_id=event_id,
            timestamp=ts,
            source=self.source_name,
            message=line,
            raw=line,
        )


class SyslogParser(LogParser):
    """Parser for /var/log/syslog and /var/log/auth.log."""

    source_name = "syslog"
    _PATTERN = re.compile(
        r"^(?P<month>\w+)\s+(?P<day>\d+)\s+(?P<time>\d{2}:\d{2}:\d{2})\s+"
        r"(?P<host>\S+)\s+(?P<proc>\S+):\s+(?P<msg>.+)$"
    )

    def parse_line(self, line: str) -> LogEvent | None:
        """Parse syslog-format line."""
        line = line.strip()
        if not line:
            return None
        m = self._PATTERN.match(line)
        ts = datetime.now(timezone.utc)
        fields: dict[str, str] = {}
        message = line
        if m:
            fields = m.groupdict()
            message = fields.get("msg", line)
        event_id = LogEvent._make_id(line, ts)
        return LogEvent(
            event_id=event_id,
            timestamp=ts,
            source=self.source_name,
            message=message,
            raw=line,
            fields=fields,
        )


class ApacheParser(LogParser):
    """Parser for Apache/Nginx combined access log."""

    source_name = "apache"
    _PATTERN = re.compile(
        r'^(?P<ip>\S+) \S+ \S+ \[(?P<time>[^\]]+)\] "(?P<request>[^"]*)" '
        r"(?P<status>\d{3}) (?P<size>\S+)"
    )

    def parse_line(self, line: str) -> LogEvent | None:
        """Parse combined access log line."""
        line = line.strip()
        if not line:
            return None
        m = self._PATTERN.match(line)
        ts = datetime.now(timezone.utc)
        fields: dict[str, str] = {}
        message = line
        if m:
            fields = m.groupdict()
            message = f"{fields['ip']} {fields['request']} {fields['status']}"
        event_id = LogEvent._make_id(line, ts)
        return LogEvent(
            event_id=event_id,
            timestamp=ts,
            source=self.source_name,
            message=message,
            raw=line,
            fields=fields,
        )


_PARSERS: dict[str, LogParser] = {
    "syslog": SyslogParser(),
    "apache": ApacheParser(),
    "generic": LogParser(),
}


def get_parser(name: str) -> LogParser:
    """Return parser by name, defaulting to generic."""
    return _PARSERS.get(name, LogParser())


# ── Alert store ────────────────────────────────────────────────────────────────

class AlertStore:
    """Thread-safe in-memory alert store with optional file persistence."""

    def __init__(self, output_path: Path | None = None) -> None:
        self._alerts: list[Alert] = []
        self._lock = threading.Lock()
        self._output_path = output_path

    def add(self, alert: Alert) -> None:
        """Add alert and optionally write to JSONL file."""
        with self._lock:
            self._alerts.append(alert)
            if self._output_path:
                with self._output_path.open("a") as fh:
                    fh.write(json.dumps(alert.to_dict()) + "\n")
        logger.warning("[ALERT] %s | %s | %s", alert.severity.value, alert.rule_name, alert.message)

    def get_all(self) -> list[Alert]:
        """Return a snapshot of all alerts."""
        with self._lock:
            return list(self._alerts)

    def count_by_severity(self) -> dict[str, int]:
        """Return counts grouped by severity."""
        counts: dict[str, int] = {s.value: 0 for s in Severity}
        with self._lock:
            for a in self._alerts:
                counts[a.severity.value] += 1
        return counts


# ── SIEM engine ────────────────────────────────────────────────────────────────

class SIEMEngine:
    """Correlates log events against detection rules and emits alerts."""

    def __init__(
        self,
        rules: list[DetectionRule] | None = None,
        alert_store: AlertStore | None = None,
        alert_callbacks: list[Callable[[Alert], None]] | None = None,
    ) -> None:
        self._rules = rules if rules is not None else list(BUILTIN_RULES)
        self._store = alert_store or AlertStore()
        self._callbacks = alert_callbacks or []

    @property
    def alert_store(self) -> AlertStore:
        """Expose the alert store."""
        return self._store

    def process_event(self, event: LogEvent) -> list[Alert]:
        """Run all rules against event; store and return any alerts fired."""
        fired: list[Alert] = []
        for rule in self._rules:
            if rule.matches(event):
                alert_id = hashlib.sha256(
                    f"{rule.name}{event.event_id}".encode()
                ).hexdigest()[:16]
                alert = Alert(
                    alert_id=alert_id,
                    rule_name=rule.name,
                    severity=rule.severity,
                    message=rule.description,
                    event=event,
                )
                self._store.add(alert)
                for cb in self._callbacks:
                    cb(alert)
                fired.append(alert)
        return fired

    def ingest_file(self, log_path: Path, parser: LogParser) -> tuple[int, int]:
        """Ingest a log file; return (lines_processed, alerts_fired)."""
        lines = events = alerts = 0
        with log_path.open(errors="replace") as fh:
            for raw_line in fh:
                lines += 1
                event = parser.parse_line(raw_line)
                if event:
                    events += 1
                    alerts += len(self.process_event(event))
        logger.info("Ingested %s: %d lines → %d events → %d alerts", log_path.name, lines, events, alerts)
        return lines, alerts

    def tail_file(self, log_path: Path, parser: LogParser, stop_event: threading.Event) -> None:
        """Tail a log file in real-time until stop_event is set."""
        with log_path.open(errors="replace") as fh:
            fh.seek(0, 2)  # seek to end
            while not stop_event.is_set():
                line = fh.readline()
                if line:
                    event = parser.parse_line(line)
                    if event:
                        self.process_event(event)
                else:
                    time.sleep(0.1)
